site_name: BIBM2025-MultiOmics
site_url: https://compbioclub.github.io/BIBM2025-MultiOmics
theme:
  name: "material"
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share\
    # - navigation.footer
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  homepage:
  social:
    - icon: fontawesome/solid/house
      link: https://compbio.club
    - icon: fontawesome/brands/github
      link: https://compbioclub.github.io/BIBM2025-MultiOmics/
  encoding: 'utf-8'

copyright: Copyright &copy; 2025 CompBioClub

# repo_url: https://github.com/compbioclub/BIBM2025-MultiOmics
# repo_name: BIBM2025-MultiOmics

plugins:
  - mknotebooks:
      encoding: 'utf-8'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - search

markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences
